### ISSUE TITLE
Additional cleanup for error-prone descriptions

### ISSUE THREAD

**Issue by Philzen** [openrewrite/rewrite-templating#93]
Following the discussion in https://github.com/openrewrite/rewrite-docs/pull/282

The error-prone template descriptions by picnic seem to need some more treatment. See this example for https://docs.openrewrite.org/recipes/tech/picnic/errorprone/refasterrules/testngtoassertjrulesrecipes:

![grafik](https://github.com/openrewrite/rewrite-templating/assets/1634615/03fe8a50-9763-4914-8be7-17d365a35567)

TODOs:

- remove leading and trailing underscore
- remove any `<p>` tags
- convert the `<pre>`-block to a markdown code block and remove the surrounding `{@code … }` custom tag

https://github.com/openrewrite/rewrite-docs/pull/282/commits/5925d43b8d3816a6df73ad9b820b49425f1807e8 sort of already describes a good test case.

**Comment by timtebeek** [comment]
Thanks for logging the issue separately; providing the context & links from the other issue for quick reference:

- The [JavaDoc for the original Refaster rule](https://github.com/PicnicSupermarket/error-prone-support/blob/d81fe19836db9f0001fb9c01370a3b808c46b440/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java#L35-L51)
- This JavaDoc is then extracted into a recipe description with some light modifications already
  https://github.com/openrewrite/rewrite-templating/blob/7eceffca8aee1e899b2614555dc938083538a20c/src/main/java/org/openrewrite/java/template/processor/RefasterTemplateProcessor.java#L439-L461
- The description is [converted into Markdown in this generator](https://github.com/openrewrite/rewrite-recipe-markdown-generator/blob/208a9d193b6fbcc06e5bcec3b6a11b425b0e4bb5/src/main/kotlin/org/openrewrite/RecipeMarkdownGenerator.kt#L651-L658), which should already account for the `_` 🤔 

All in all this will require some fixes both here and in the markdown generator, before they show up as fixed in the docs.

**Comment by timtebeek** [comment]
Thanks again @Philzen ! Next version of Error-Prone Support and the docs should see these improvements.
